name: Deploy as Container

on:
#  repository_dispatch
 push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:  
    - name: "Checkout GitHub repository"
      uses: actions/checkout@v2
    - name: "Login to Azure"
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy GitHub Runner to Azure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/container/deploy.sh
          $GITHUB_WORKSPACE/container/deploy.sh
      env:
        RG_NAME: "github-runner-docker-${{github.run_number}}"
        RG_LOCATION: "WestEurope"
        GH_TOKEN: ${{secrets.GH_TOKEN_REPO}}
        GH_REPOSITORY: ${{github.repository}}
  
  test:
    runs-on: [self-hosted, Linux, Azure]
    needs: deploy

    steps: 
    - name: "Test GitHub Runner on Azure"
      run:  |
        hostname -I | awk '{print "GitHub Runner Private IP:\t", $1}'