name: Create self hosted runner

on:
  push:
    branches: [ master ]

jobs:
  createSelfHostedRunner:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_registration_token
        with:
          route: POST /orgs/:org/actions/runners/registration-token
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_registration_token.outputs.data }}"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID ",
        echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER "
