name: Deploy GitHub Runner to Azure

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:  
    - name: "Checkout GitHub repository"
      uses: actions/checkout@v2
    - name: "Login to Azure"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: "Deploy GitHub Runner to Azure"
      run:  |
        ./deploy.sh ${{ secrets.GITHUB_TOKEN }}
    - name: "Logout of Azure"
      run: |
        az logout
  test:
    runs-on: self-hosted, Azure

    steps: 
    - name: "Test GitHub Runner on Azure"
      run:  |
        hostname -I | awk '{print "GitHub Runner Private IP:\t", $1}'
  
