name: Deploy GitHub Runner to Azure

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2
    - name: Deploy GitHub RUnenr
      run: ./deploy.sh ${{ secrets.GITHUB_TOKEN }}
