name: Create self hosted runner

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID ",
        echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER "
