name: Foo

on:
  repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:  
      - name: "Foo"
        run:  |
            echo -e "${BLUE}${BASE_NAME}${NC}"
    env:
      BASE_NAME: "Foo-${{ github.run_number }}"	
          
env:
  BLUE: '\033[0;34m'
  NC: '\033[0m' # No Color
  
