name: Test GitHub Runner on Azure

on:
  repository_dispatch

jobs:
  test:
    runs-on: [self-hosted, Linux, Azure]
    
    steps: 
    - name: "Test GitHub Runner on Azure"
      run:  |
        hostname -I | awk '{print "GitHub Runner Private IP:\t", $1}'
  
